

# Configuração do MongoDB

service_name = MongoClient('mongodb+srv://user_01:sucesso1807@cluster0.slfd3no.mongodb.net/')
db = client['futebol']
collection = db['atletas']
colp = db['pontuacao']
colc = db['cartoes']
colcc_config = db['config']

